apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.env }}-{{ .Values.name }}
  namespace: {{ .Values.env }}
  labels:
    app: {{ .Values.env }}-{{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.env }}-{{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.env }}-{{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.env }}-{{ .Values.name }}
          image: "gcr.io/koshelev/flask-converter:{{ .Values.tag }}"
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 5
