apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-upstream
  namespace: {{ .Values.env }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: http
      port: 80
      targetPort: 80