apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env }}-{{ .Values.name }}-upstream
  namespace: {{ .Values.env }}
spec:
  selector:
    app: {{ .Values.env }}-{{ .Values.name }}
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: 80